#!/bin/sh
#
# WebRelay command line

KRSH_POWER_HOSTNAME=${KRSH_POWER_HOSTNAME:-192.168.1.2}

state () {
  > /dev/null curl -s http://$KRSH_POWER_HOSTNAME/state.xml?relayState=$1
}

case $1 in
  poweron) state 1 ;;
  poweroff) state 0 ;;
  reboot) state 0 ; sleep 2 ; state 1 ;;
  *) exit 1 ;;
esac
