#!/bin/sh
#
# krsh power driver for Synaccess netBooter NP-08

KRSH_POWER_USER=${KRSH_POWER_USER:-admin}
KRSH_POWER_PASSWORD=${KRSH_POWER_PASSWORD:-admin}
KRSH_POWER_HOSTNAME=${KRSH_POWER_HOSTNAME:-netbooter}
KRSH_POWER_PORT=${KRSH_POWER_PORT:-0}

print () {
  [ -n "$QUIET" ] || printf "$@"
}

# get <page>
get () {
  # FIXME cannot error out if the host is unavailable
  curl -Ss -u $KRSH_POWER_USER:$KRSH_POWER_PASSWORD http://$KRSH_POWER_HOSTNAME/$1
}

status () {
  get synOpStatus.shtml | grep pwrRb$KRSH_POWER_PORT.cgi | grep -oP '(?<=led)on|off(?=\.gif)'
}

sw () {
  >/dev/null get pwrSw$KRSH_POWER_PORT.cgi # toggles on/off
}

rb () {
  >/dev/null get pwrRb$KRSH_POWER_PORT.cgi # toggles twice
}

# wait <status>...
wait () {
  print $KRSH_POWER_PORT
  for i
  do
    while true
    do
      # Wait and trigger a status request otherwise the action may be ignored
      print .
      sleep .5
      [ $(status) = $i ] && break
    done
    print $i
  done
  print "\n"
}

on () {
  if [ $(status) = off ]
  then
    sw
    wait on
  fi
}

off () {
  if [ $(status) = on ]
  then
    sw
    wait off
  fi
}

reboot () {
  if [ $(status) = on ]
  then
    rb
    wait off on
  else
    sw
    wait on
  fi
}

case $1 in
  poweron) on ;;
  poweroff) off ;;
  reboot) reboot ;;
  *) exit 1 ;;
esac
