#!/bin/sh

KRSH_TTY_DEVICE=${KRSH_TTY_DEVICE:-/dev/null}
KRSH_TTY_SESSION=/tmp/dtach.picocom.$(basename $KRSH_TTY_DEVICE).session
KRSH_TTY_BAUDRATE=${KRSH_TTY_BAUDRATE:-115200}

echo "Press Enter to continue, then ^\ to detach."
read

exec dtach -A $KRSH_TTY_SESSION picocom -b $KRSH_TTY_BAUDRATE $KRSH_TTY_DEVICE
